/**
 * Seed the agent preset on activation.
 *
 * Why this exists: the npm package carries the settings page, and every plugin
 * storefront installs a plugin with one command —
 * `dsh plugin --profile web add dsh-custom-mode`. Without this module that single
 * command produces a settings page whose preset does not exist on disk: the page opens
 * on "composition file not found", and the mode cannot even be picked for a new session.
 * A one-command install has to be a complete one.
 *
 * Why not a `postinstall` script: pnpm ≥ 10 blocks install scripts by default, and
 * marketplaces list them as a supply-chain risk. Seeding when the plugin activates is
 * both more reliable and less alarming.
 *
 * Three rules, in order of importance:
 *
 *  1. **Never overwrite.** `prompt.md` is the user's own text and `agent.cordis.yml` may
 *     have been generated by the settings page. Only missing files are written.
 *  2. **Never throw.** A read-only or otherwise unwritable `DSH_HOME` must not keep dsh
 *     from booting; the settings page reports the problem instead.
 *  3. **Idempotent.** A second activation writes nothing and changes nothing.
 */

import { copyFileSync, existsSync, mkdirSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

/** The files a working preset needs. Order is the order they are written. */
export const PRESET_FILES = [
  'agent.cordis.yml',
  'preset.yml',
  'prompt.md',
  'prompt-reader.mjs',
  'prompt-tool.mjs',
]

/** Directory of the packaged copy: `editor/preset/` beside this module. */
export function packagedPresetDir() {
  return join(dirname(fileURLToPath(import.meta.url)), 'preset')
}

/** `error` as a readable string, without assuming it is an Error. */
function describe(error) {
  return String((error && error.message) || error)
}

/**
 * Fill in the preset files missing from `presetDir`, copying from `sourceDir`.
 *
 * @param {string} presetDir - the installed preset directory (`$DSH_HOME/.agent-presets/custom`).
 * @param {string} [sourceDir] - the packaged copy to copy from.
 * @returns {{created: string[], kept: string[], errors: string[]}} what happened, per file.
 */
export function seedPreset(presetDir, sourceDir = packagedPresetDir()) {
  const created = []
  const kept = []
  const errors = []

  if (typeof presetDir !== 'string' || presetDir === '') {
    return { created, kept, errors: ['没有可用的 preset 目录路径'] }
  }
  if (!existsSync(sourceDir)) {
    return { created, kept, errors: [`包内预设目录不存在: ${sourceDir}`] }
  }
  try {
    mkdirSync(presetDir, { recursive: true })
  } catch (error) {
    // A read-only DSH_HOME lands here. Report it; do not attempt anything else.
    return { created, kept, errors: [`无法创建 ${presetDir}: ${describe(error)}`] }
  }

  for (const name of PRESET_FILES) {
    const target = join(presetDir, name)
    if (existsSync(target)) {
      kept.push(name)
      continue
    }
    const source = join(sourceDir, name)
    if (!existsSync(source)) {
      errors.push(`包内缺少 ${name}`)
      continue
    }
    try {
      copyFileSync(source, target)
      created.push(name)
    } catch (error) {
      errors.push(`写入 ${name} 失败: ${describe(error)}`)
    }
  }
  return { created, kept, errors }
}

/**
 * Seed and report, in the form the host half logs.
 *
 * Silent when the preset was already complete — the common case after the first
 * activation, and after `./install.sh`, which copies the same files itself.
 *
 * @param {string} presetDir - destination preset directory.
 * @param {(message: string) => void} [log] - error sink (defaults to console.error).
 * @param {(message: string) => void} [info] - info sink (defaults to console.log).
 * @param {string} [sourceDir] - packaged template to copy from (defaults to `preset/` beside this module).
 * @returns {{created: string[], kept: string[], errors: string[]}}
 */
export function seedPresetWithLog(presetDir, log = console.error, info = console.log, sourceDir = packagedPresetDir()) {
  let result
  try {
    result = seedPreset(presetDir, sourceDir)
  } catch (error) {
    // seedPreset is written not to throw; this is a last-resort guard so that a bug here
    // can never stop the host from booting.
    log(`custom-mode: 播种 preset 时出现意外错误（已忽略）: ${describe(error)}`)
    return { created: [], kept: [], errors: [describe(error)] }
  }
  if (result.created.length > 0) {
    info(`custom-mode: 已播种 preset 到 ${presetDir}（新建 ${result.created.length} 个文件: ${result.created.join(', ')}）`)
  }
  for (const error of result.errors) {
    log(`custom-mode: preset 播种未完成 —— ${error}`)
  }
  if (result.errors.length > 0) {
    log(`custom-mode: 设置页仍可打开，但组成文件可能缺失，见 docs/TROUBLESHOOTING.zh.md`)
  }
  return result
}
